### ISSUE TITLE
Question 2

### ISSUE THREAD

**Issue by ghost** [skidlamer/skidlamer.github.io#13]
Every time all the hacks get patched and you have to fix the hack, what do you normally have to change in your script? Every time you update your script, much of it seems to stay the same. Once I understand how to defeat the patch, I would love to collaborate with you. I already know how to code in Javascript. It's just that I have no experience with client-side modification/enhancement.

 - Early Thanks

Or if you have the time, make a tutorial?

**Comment by ghost** [comment]
Bump^^^ @skidlamer

**Comment by emlinhax** [comment]
@Helixable Since the main game script is encrypted, on a small patch the only thing he might do is update the regex.. thats all. And on a big update he changes functions entirely. I dont know

**Comment by ghost** [comment]
Thanks for the info.
