### ISSUE TITLE
Very Lag

### ISSUE THREAD

**Issue by Alessandro600** [skidlamer/skidlamer.github.io#2]
This aimbot makes a lot of lagging. And when I try to use it with a gun I can't because it fires a bullet per second

**Comment by billythejew456** [comment]
of course hes here man your a fag you know that your just gonna steal it and say its gaming chair

**Comment by Alessandro600** [comment]
> of course hes here man your a fag you know that your just gonna steal it and say its gaming chair

I'm giving him tips to improve it. I don't take other people's projects. Gay
