### ISSUE TITLE
 ‌

### ISSUE THREAD

**Issue by n2m2** [skidlamer/skidlamer.github.io#20]

**Comment by Hey2020** [comment]
Fixed! Use Normal Chrome
also clear cache and cookies

**Comment by Hey2020** [comment]
Failed in brave browser with error : Failed to load resource: net::ERR_TOO_MANY_REDIRECTS
Tried fixes:
Clear cache and cookies
Reinstall Brave

**Comment by Aether06** [comment]
i remember a hack that had a feature that gave every skin in the game

**Comment by Hey2020** [comment]
Use Slim-jet Browser and if problems occur clear cache and cookies
